spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.103.142.85:3306/carmanager?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=CTT
    username: root
    password: Luan123456
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  jmx:
    enabled: false


mybatis:
  mapper-locations: classpath*:mapper/*.xml
server:
  port: 8090
